# Generated by Django 4.0.3 on 2022-04-07 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Os',
            fields=[
                ('id_os', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, verbose_name='Sistema operativo')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sistema operativo',
                'verbose_name_plural': 'Sistemas operativos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Sistema operativo')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de computadora',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ns', models.CharField(default='DEFAULT VALUE', help_text='Numero serial', max_length=20, verbose_name='Numero serial')),
                ('discoDuro', models.CharField(help_text='Tamaño de disco duro', max_length=50, verbose_name='Tamaño de disco duro')),
                ('folio', models.CharField(default='N/A', help_text='Etiqueta en la computadora', max_length=20, verbose_name='Folio de la computadora')),
                ('ram', models.CharField(help_text='Cantidad de RAM instalada', max_length=10, verbose_name='Ram instalada en la computadora')),
                ('ip_numero', models.CharField(help_text='Numero serial', max_length=16, verbose_name='Direccion IPV4')),
                ('comentarios', models.CharField(default='N/A', help_text='Comentarios hacerca de la computadora', max_length=100, verbose_name='Comentarios acerca de la computadora')),
                ('is_active', models.BooleanField(default=True)),
                ('so', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipo.os')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipo.tipo')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['tipo'],
            },
        ),
    ]
