# Generated by Django 4.0.3 on 2022-04-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de computadora', 'verbose_name_plural': 'Tipos de computadoras'},
        ),
        migrations.AddField(
            model_name='equipo',
            name='fabricante',
            field=models.CharField(default='N/A', help_text='Fabircante', max_length=30, verbose_name='Fabricante de la computadora'),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Tipo de computadora'),
        ),
    ]
