# Generated by Django 4.0.3 on 2022-04-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0002_alter_tipo_options_equipo_fabricante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='prestado',
            field=models.BooleanField(default=False),
        ),
    ]
