# Generated by Django 4.0.3 on 2022-04-08 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0003_equipo_prestado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id_fabricante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre del fabricante')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FabriFabricantes',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(default='N/A', help_text='Modelo', max_length=30, verbose_name='Modelo de la computadora'),
        ),
        migrations.AlterField(
            model_name='os',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Sistema operativo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fabricante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipo.fabricante'),
        ),
    ]
