# Generated by Django 4.0.3 on 2022-04-08 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0004_fabricante_equipo_modelo_alter_os_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabricante',
            options={'ordering': ['nombre'], 'verbose_name': 'Fabricante'},
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='is_active',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='fabricante',
            old_name='is_active',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='os',
            old_name='is_active',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='tipo',
            old_name='is_active',
            new_name='estado',
        ),
    ]
