# Generated by Django 4.0.3 on 2022-04-10 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='So',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('ns', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('discoDuro', models.CharField(max_length=30)),
                ('folio', models.CharField(blank=True, default='N/A', max_length=15, null=True)),
                ('ram', models.CharField(max_length=10)),
                ('ip_numero', models.CharField(max_length=15)),
                ('Prestado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo.fabricante')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo.modelo')),
                ('so', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo.so')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo.tipo')),
            ],
        ),
    ]
