# Generated by Django 4.0.3 on 2022-04-12 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ['ns'], 'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.AlterModelOptions(
            name='fabricante',
            options={'verbose_name': 'Fabricante', 'verbose_name_plural': 'Fabricantes'},
        ),
        migrations.AlterModelOptions(
            name='modelo',
            options={'verbose_name': 'Modelo de la computadora', 'verbose_name_plural': 'Modelos de las computadoras'},
        ),
        migrations.AlterModelOptions(
            name='so',
            options={'verbose_name': 'Sistema operativo', 'verbose_name_plural': 'Sistemas operativos'},
        ),
        migrations.AlterModelOptions(
            name='tipo',
            options={'verbose_name': 'Tipo de computadora', 'verbose_name_plural': 'Tipos de computadoras'},
        ),
    ]
