# Generated by Django 4.0.3 on 2022-04-12 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0006_impresora_escaner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='fabricante',
        ),
        migrations.AddField(
            model_name='modelo',
            name='fabricante',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='equipo.fabricante'),
        ),
    ]
