# Generated by Django 4.0.3 on 2022-04-12 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0007_remove_equipo_fabricante_modelo_fabricante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='fabricante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo.fabricante'),
        ),
    ]
