# Generated by Django 4.0.3 on 2022-04-12 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0008_alter_modelo_fabricante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrega', models.DateField(auto_now=True)),
                ('fecha_devolucion', models.DateField(auto_now=True, verbose_name='Fecha de creación')),
                ('qr_code', models.ImageField(upload_to='CodigosQR')),
                ('activo', models.BooleanField(default=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo.equipo')),
                ('usario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo.usuario')),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historiales',
            },
        ),
    ]
