# Generated by Django 4.0.3 on 2022-04-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0009_historial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historial',
            options={'verbose_name': 'Historial', 'verbose_name_plural': 'Historial'},
        ),
        migrations.RenameField(
            model_name='departamento',
            old_name='id',
            new_name='id_departamento',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='modelo',
            new_name='id_modelo',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='so',
            new_name='id_so',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='tipo',
            new_name='id_tipo',
        ),
        migrations.RenameField(
            model_name='escaner',
            old_name='fabricante',
            new_name='id_fabricante',
        ),
        migrations.RenameField(
            model_name='escaner',
            old_name='modelo',
            new_name='id_modelo',
        ),
        migrations.RenameField(
            model_name='fabricante',
            old_name='id',
            new_name='id_fabricante',
        ),
        migrations.RenameField(
            model_name='historial',
            old_name='equipo',
            new_name='ns',
        ),
        migrations.RenameField(
            model_name='impresora',
            old_name='fabricante',
            new_name='id_fabricante',
        ),
        migrations.RenameField(
            model_name='impresora',
            old_name='modelo',
            new_name='id_modelo',
        ),
        migrations.RenameField(
            model_name='modelo',
            old_name='fabricante',
            new_name='id_fabricante',
        ),
        migrations.RenameField(
            model_name='modelo',
            old_name='id',
            new_name='id_modelo',
        ),
        migrations.RenameField(
            model_name='permisos',
            old_name='id',
            new_name='id_permisos',
        ),
        migrations.RenameField(
            model_name='so',
            old_name='id',
            new_name='id_so',
        ),
        migrations.RenameField(
            model_name='tipo',
            old_name='id',
            new_name='id_tipo',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='id',
            new_name='id_usuario',
        ),
    ]
