# Generated by Django 4.0.3 on 2022-04-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0010_alter_historial_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historial',
            old_name='usario',
            new_name='id_usario',
        ),
    ]
