# Generated by Django 4.0.3 on 2022-04-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0011_rename_usario_historial_id_usario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricante',
            name='nombre',
            field=models.CharField(help_text='Numero serial', max_length=200, verbose_name='Numero serial'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='fecha_devolucion',
            field=models.DateField(verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='fecha_entrega',
            field=models.DateField(auto_now=True, verbose_name='Fecha de entrega'),
        ),
    ]
