# Generated by Django 4.0.3 on 2022-04-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0012_alter_fabricante_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historial',
            old_name='id_usario',
            new_name='id_usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='departamento',
            new_name='id_departamento',
        ),
        migrations.AlterField(
            model_name='historial',
            name='fecha_devolucion',
            field=models.DateField(verbose_name='Fecha de devolucion'),
        ),
    ]
