# Generated by Django 4.0.3 on 2022-04-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0014_remove_historial_activo_historial_recibido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='aio',
        ),
        migrations.AddField(
            model_name='usuario',
            name='allow',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='ns',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
