# Generated by Django 4.0.3 on 2022-04-28 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0016_alter_historial_fecha_devolucion_alter_usuario_allow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='equipo',
            name='basura_electronica',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historial',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo.usuario', verbose_name='Nombre del usuario'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='ns',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo.equipo', verbose_name='Numero Serial de la computadora'),
        ),
    ]
