# Generated by Django 4.0.3 on 2022-04-29 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0018_usuario_puesto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escaner',
            name='id_fabricante',
        ),
        migrations.RemoveField(
            model_name='impresora',
            name='id_fabricante',
        ),
    ]
